<?php

use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;

/**
 * @file
 * Contains embargoes.module.
 */

/**
 * Implements hook_node_view().
 */
function embargoes_node_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $nid = $entity->get('nid')->value;
  $ip = \Drupal::request()->getClientIp();
  $user = \Drupal::currentUser();
  $embargoes = \Drupal::service('embargoes.embargoes')->getActiveNodeEmbargoesByNode($nid, $ip, $user);
  if (!empty($embargoes)) {
    throw new AccessDeniedHttpException();
  }
}
